name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test with Go ${{ matrix.go }} on OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    # Test with all supported Go versions on all OSes
    strategy:
      matrix:
        go: [ '1.21', '1.20', '1.18' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v -coverprofile coverage.out ./...

      - name: Update coverage badge
        uses: ncruces/go-coverage-report@main
        with:
          coverage-file: coverage.out
          reuse-go: true
          amend: true
          report: true
          chart: true
        if: |
          github.event_name == 'push' &&
          matrix.go == '1.18' &&
          matrix.os == 'ubuntu-latest'
        continue-on-error: true
